version: '3'

services:
  storage:
      container_name: 'broad_mysql'
      image: mysql:latest
      command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
      restart: always
      ports:
        - 3306:3306      
      volumes:
        - ./docker/provision/mysql/init:/docker-entrypoint-initdb.d
      environment:
        MYSQL_ROOT_PASSWORD: pass

  cache:
    container_name: 'broad_cache'
    image: redis
    restart: always
    ports:
      - 6379:6379
volumes:
  broad-volume: null

