version: '3'

services:
  storage:
    container_name: 'broad_mysql'
    image: mysql:latest
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: pepperlocal
    volumes:
      - broad-volume:/var/lib/mysql

  cache:
    container_name: 'broad_cache'
    image: redis
    restart: always
    ports:
      - 6379:6379

volumes:
  broad-volume: null
